### ISSUE TITLE
Unclear image on iPhone Chrome

### ISSUE THREAD

**Issue by ksyusha123** [ekaterinburgdev/map#91]
In some cases image becomes "dirty"
![photo_2023-08-11_15-08-40](https://github.com/ekaterinburgdev/map/assets/72920390/7cf92f72-5f73-4065-bb6a-063245f6f47b)

**Comment by circus2271** [comment]
> In some cases image becomes "dirty"
> ![photo_2023-08-11_15-08-40](https://github.com/ekaterinburgdev/map/assets/72920390/7cf92f72-5f73-4065-bb6a-063245f6f47b)
> 

Hi

I don't know, but maybe it's a telegram image compression? Telegram reduces image quality of uploaded images

**Comment by Omelekhin** [comment]
This bug seems to have been fixed or is no longer relevant.
![IMG_3372](https://github.com/ekaterinburgdev/map/assets/3252827/07c8072d-cf9f-4000-99f0-9e9cd8f00ca3)
